# Site settings
name: Akshay Easwaran
title: "Akshay Easwaran"
description: A software engineer with a mild Atlanta sports addiction.
meta_description: "Akshay Easwaran - A software engineer with a mild Atlanta sports addiction"

author: Akshay Easwaran
email: akeaswaran@me.com
domain_name: 'http://akeaswaran.me'
github_username: akeaswaran

baseurl: # the subpath of your site, e.g. /blog
url: "http://akeaswaran.me" # the base hostname & protocol for your site

google_analytics_id: 'UA-72482077-2'

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:title/

sass:
    style: compressed

exclude: [vendor]

collections:
  drafts:
    output: true

defaults:
    -
        scope:
            path: "pages" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
