# Site settings
title: Akshay Easwaran
email: akeaswaran@me.com
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts and musings.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://akeaswaran.me" # the base hostname & protocol for your site
twitter_username: akeaswaran
github_username:  akeaswaran

# Build settings
markdown: kramdown

paginate: 4

author: Akshay Easwaran

gems: [jekyll-paginate]
